#
# for huaqin misc info
#

# huaqin added by SunXunou for HMD_ZQL1838 at 20200518 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK)   += sim_tray/
# huaqin added by SunXunou for HMD_ZQL1838 at 20200518 end
# huaqin added by zhouzichun for HMD_ZQL1838 at 20200518 start
obj-$(CONFIG_HW_INFO)   += hw_info/
# huaqin added by zhouzichun for HMD_ZQL1838 at 20200518 end
# huaqin added for DRSTRANGE-346 by yutao at 2020/06/19 start
obj-$(CONFIG_RECORD_CRASH_INFO)   += crash_record/
# huaqin added for DRSTRANGE-346 by yutao at 2020/06/19 end

