# Makefile for the focaltech touchscreen drivers.


obj-y 	+=  focaltech_core.o
obj-y 	+=  focaltech_ex_fun.o
obj-y 	+=  focaltech_ex_mode.o
obj-y 	+=  focaltech_gesture.o
obj-y 	+=  focaltech_esdcheck.o
obj-y    +=  focaltech_point_report_check.o
# Huaqin add for HS70-142 ito test by gaozhengwei at 2019/10/08 start
obj-y    +=  focaltech_test/
# Huaqin add for HS70-142 ito test by gaozhengwei at 2019/10/08 end

obj-y    +=  focaltech_spi.o
obj-y 	+=  focaltech_flash.o