#
# for huaqin sim tray status check
#

# huaqin added by SunXunou for HMD_ZQL1838 at 20200518 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK) += sim_tray.o
# huaqin added by SunXunou for HMD_ZQL1838 at 20200518 end
